[package]
name = "tracecon"
version = "0.1.0"
authors = ["Magnus Kulke <mkulke@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
libbpf-rs = "0.10"
libc = "0.2"
structopt = "0.3"
ctrlc = "3.1"

[build-dependencies]
libbpf-cargo = "0.7"
